import BackButton from "../../../components/Generic/BackButton/BackButton";

const PFENG = () => {
  return (
    <div>
      <BackButton pageTitle={"How WOW!Dropbox Ensures Fairness"} />

      <h2>Provably Fair</h2>
      <p>
        To make sure every Dropbox unboxing is both fair and transparent, we use
        a <strong>provably fair system</strong>. This system creates a random
        result using three independent components, allowing you to{" "}
        <strong>verify each outcome on your own</strong>.
      </p>
      <p>
        It’s similar to playing a physical game with dice or cards — where you
        know the dice have six sides or the deck has 52 cards. Online, we follow
        the same logic to ensure that every result is completely random and
        trustworthy.
      </p>

      <h2>How Results Are Determined</h2>
      <p>Each unboxing outcome is based on three key factors:</p>
      <ul>
        <li>
          <strong>Your Hand:</strong> A unique code generated from your input.
          You can change this code and even compare it with other players’
          codes.
        </li>
        <li>
          <strong>Our Hand:</strong> A hidden code that is revealed only after
          the result is shown.
        </li>
        <li>
          <strong>Play Count:</strong> The number of times you’ve played, which
          increases with every game.
        </li>
      </ul>
      <p>
        These three elements combine to generate a roll number between 0 and
        100,000,000. This number determines the item you receive.
      </p>
      <p>The system uses the following seeds to calculate each outcome:</p>
      <ul>
        <li>
          <strong>Client Seed:</strong> A user-defined value that you can view
          and change at any time.
        </li>
        <li>
          <strong>Server Seed:</strong> A secure, encrypted value generated by
          us. You’ll see a hashed version before playing; after the game, the
          original seed is revealed so you can confirm the result was fair.
        </li>
        <li>
          <strong>Play Count:</strong> Ensures every game is unique, even if the
          same seeds are used.
        </li>
      </ul>
      <p>
        Thanks to this structure, every roll is not only random but also
        verifiable. Below is a sample code snippet you can use to check any
        previous roll:
      </p>
    </div>
  );
};

export default PFENG;
