export const CountryData = [
  {
    id: 1,
    country: "Austria",
    phoneCode: "+43",
    states: [
      { id: "AT-1", name: "Burgenland" },
      { id: "AT-2", name: "Carinthia" },
      { id: "AT-3", name: "Lower Austria" },
      { id: "AT-4", name: "Upper Austria" },
      { id: "AT-5", name: "Salzburg" },
      { id: "AT-6", name: "Styria" },
      { id: "AT-7", name: "Tyrol" },
      { id: "AT-8", name: "Vorarlberg" },
      { id: "AT-9", name: "Vienna" },
    ],
  },
  {
    id: 2,
    country: "Belgium",
    phoneCode: "+32",
    states: [
      { id: "BE-BRU", name: "Brussels-Capital Region" },
      { id: "BE-VLG", name: "Flanders" },
      { id: "BE-WAL", name: "Wallonia" },
    ],
  },
  {
    id: 3,
    country: "Bulgaria",
    phoneCode: "+359",
    states: [
      { id: "BG-01", name: "Blagoevgrad" },
      { id: "BG-02", name: "Burgas" },
      { id: "BG-08", name: "Dobrich" },
      { id: "BG-07", name: "Gabrovo" },
      { id: "BG-26", name: "Haskovo" },
      { id: "BG-09", name: "Kardzhali" },
      { id: "BG-10", name: "Kyustendil" },
      { id: "BG-11", name: "Lovech" },
      { id: "BG-12", name: "Montana" },
      { id: "BG-13", name: "Pazardzhik" },
      { id: "BG-14", name: "Pernik" },
      { id: "BG-15", name: "Pleven" },
      { id: "BG-16", name: "Plovdiv" },
      { id: "BG-17", name: "Razgrad" },
      { id: "BG-18", name: "Ruse" },
      { id: "BG-27", name: "Shumen" },
      { id: "BG-19", name: "Silistra" },
      { id: "BG-20", name: "Sliven" },
      { id: "BG-21", name: "Smolyan" },
      { id: "BG-23", name: "Sofia" },
      { id: "BG-22", name: "Sofia Province" },
      { id: "BG-24", name: "Stara Zagora" },
      { id: "BG-25", name: "Targovishte" },
      { id: "BG-03", name: "Varna" },
      { id: "BG-04", name: "Veliko Tarnovo" },
      { id: "BG-05", name: "Vidin" },
      { id: "BG-06", name: "Vratsa" },
      { id: "BG-28", name: "Yambol" },
    ],
  },
  {
    id: 4,
    country: "Croatia",
    phoneCode: "+385",
    states: [
      { id: "HR-01", name: "Zagreb County" },
      { id: "HR-02", name: "Krapina-Zagorje County" },
      { id: "HR-03", name: "Sisak-Moslavina County" },
      { id: "HR-04", name: "Karlovac County" },
      { id: "HR-05", name: "Varaždin County" },
      { id: "HR-06", name: "Koprivnica-Križevci County" },
      { id: "HR-07", name: "Bjelovar-Bilogora County" },
      { id: "HR-08", name: "Primorje-Gorski Kotar County" },
      { id: "HR-09", name: "Lika-Senj County" },
      { id: "HR-10", name: "Virovitica-Podravina County" },
      { id: "HR-11", name: "Požega-Slavonia County" },
      { id: "HR-12", name: "Brod-Posavina County" },
      { id: "HR-13", name: "Zadar County" },
      { id: "HR-14", name: "Osijek-Baranja County" },
      { id: "HR-15", name: "Šibenik-Knin County" },
      { id: "HR-16", name: "Vukovar-Srijem County" },
      { id: "HR-17", name: "Split-Dalmatia County" },
      { id: "HR-18", name: "Istria County" },
      { id: "HR-19", name: "Dubrovnik-Neretva County" },
      { id: "HR-20", name: "Međimurje County" },
      { id: "HR-21", name: "Zagreb" },
    ],
  },
  {
    id: 5,
    country: "Cyprus",
    phoneCode: "+357",
    states: [
      { id: "CY-01", name: "Famagusta" },
      { id: "CY-02", name: "Kyrenia" },
      { id: "CY-03", name: "Larnaca" },
      { id: "CY-04", name: "Nicosia" },
      { id: "CY-05", name: "Limassol" },
      { id: "CY-06", name: "Paphos" },
    ],
  },
  {
    id: 6,
    country: "Czech Republic",
    phoneCode: "+420",
    states: [
      { id: "CZ-JC", name: "South Bohemia" },
      { id: "CZ-JM", name: "South Moravia" },
      { id: "CZ-KA", name: "Karlovy Vary" },
      { id: "CZ-KR", name: "Hradec Králové" },
      { id: "CZ-LI", name: "Liberec" },
      { id: "CZ-MO", name: "Moravia-Silesia" },
      { id: "CZ-OL", name: "Olomouc" },
      { id: "CZ-PA", name: "Pardubice" },
      { id: "CZ-PL", name: "Plzeň" },
      { id: "CZ-PR", name: "Prague" },
      { id: "CZ-ST", name: "Central Bohemia" },
      { id: "CZ-US", name: "Ústí nad Labem" },
      { id: "CZ-VY", name: "Vysočina" },
      { id: "CZ-ZL", name: "Zlín" },
    ],
  },
  {
    id: 7,
    country: "Denmark",
    phoneCode: "+45",
    states: [
      { id: "DK-84", name: "Capital Region of Denmark" },
      { id: "DK-82", name: "Central Denmark Region" },
      { id: "DK-81", name: "North Denmark Region" },
      { id: "DK-83", name: "Region of Southern Denmark" },
      { id: "DK-85", name: "Region Zealand" },
    ],
  },
  {
    id: 8,
    country: "Estonia",
    phoneCode: "+372",
    states: [
      { id: "EE-37", name: "Harju County" },
      { id: "EE-39", name: "Hiiu County" },
      { id: "EE-44", name: "Ida-Viru County" },
      { id: "EE-51", name: "Järva County" },
      { id: "EE-49", name: "Jõgeva County" },
      { id: "EE-59", name: "Lääne County" },
      { id: "EE-57", name: "Lääne-Viru County" },
      { id: "EE-67", name: "Pärnu County" },
      { id: "EE-65", name: "Põlva County" },
      { id: "EE-70", name: "Rapla County" },
      { id: "EE-74", name: "Saare County" },
      { id: "EE-78", name: "Tartu County" },
      { id: "EE-82", name: "Valga County" },
      { id: "EE-84", name: "Viljandi County" },
      { id: "EE-86", name: "Võru County" },
    ],
  },
  {
    id: 9,
    country: "Finland",
    phoneCode: "+358",
    states: [
      { id: "FI-01", name: "Åland" },
      { id: "FI-02", name: "South Karelia" },
      { id: "FI-03", name: "South Ostrobothnia" },
      { id: "FI-04", name: "South Savo" },
      { id: "FI-05", name: "Kainuu" },
      { id: "FI-06", name: "Central Finland" },
      { id: "FI-07", name: "Kymenlaakso" },
      { id: "FI-08", name: "Lapland" },
      { id: "FI-09", name: "Pirkanmaa" },
      { id: "FI-10", name: "Päijät-Häme" },
      { id: "FI-11", name: "Satakunta" },
      { id: "FI-12", name: "North Karelia" },
      { id: "FI-13", name: "Northern Ostrobothnia" },
      { id: "FI-14", name: "Northern Savo" },
      { id: "FI-15", name: "Ostrobothnia" },
      { id: "FI-16", name: "Central Ostrobothnia" },
      { id: "FI-17", name: "Uusimaa" },
      { id: "FI-18", name: "Varsinais-Suomi" },
    ],
  },
  {
    id: 10,
    country: "France",
    phoneCode: "+33",
    states: [
      { id: "FR-ARA", name: "Auvergne-Rhône-Alpes" },
      { id: "FR-BFC", name: "Bourgogne-Franche-Comté" },
      { id: "FR-BRE", name: "Brittany" },
      { id: "FR-CVL", name: "Centre-Val de Loire" },
      { id: "FR-GES", name: "Grand Est" },
      { id: "FR-HDF", name: "Hauts-de-France" },
      { id: "FR-IDF", name: "Île-de-France" },
      { id: "FR-NOR", name: "Normandy" },
      { id: "FR-NAQ", name: "Nouvelle-Aquitaine" },
      { id: "FR-OCC", name: "Occitanie" },
      { id: "FR-PDL", name: "Pays de la Loire" },
      { id: "FR-PAC", name: "Provence-Alpes-Côte d'Azur" },
      { id: "FR-COR", name: "Corsica" },
    ],
  },
  {
    id: 11,
    country: "Germany",
    phoneCode: "+49",
    states: [
      { id: "DE-BW", name: "Baden-Württemberg" },
      { id: "DE-BY", name: "Bavaria" },
      { id: "DE-BE", name: "Berlin" },
      { id: "DE-BB", name: "Brandenburg" },
      { id: "DE-HB", name: "Bremen" },
      { id: "DE-HH", name: "Hamburg" },
      { id: "DE-HE", name: "Hesse" },
      { id: "DE-MV", name: "Mecklenburg-Vorpommern" },
      { id: "DE-NI", name: "Lower Saxony" },
      { id: "DE-NW", name: "North Rhine-Westphalia" },
      { id: "DE-RP", name: "Rhineland-Palatinate" },
      { id: "DE-SL", name: "Saarland" },
      { id: "DE-SN", name: "Saxony" },
      { id: "DE-ST", name: "Saxony-Anhalt" },
      { id: "DE-SH", name: "Schleswig-Holstein" },
      { id: "DE-TH", name: "Thuringia" },
    ],
  },
  {
    id: 12,
    country: "Greece",
    phoneCode: "+30",
    states: [
      { id: "GR-A", name: "East Macedonia and Thrace" },
      { id: "GR-B", name: "Central Macedonia" },
      { id: "GR-C", name: "West Macedonia" },
      { id: "GR-D", name: "Epirus" },
      { id: "GR-E", name: "Thessaly" },
      { id: "GR-F", name: "Ionian Islands" },
      { id: "GR-G", name: "West Greece" },
      { id: "GR-H", name: "Central Greece" },
      { id: "GR-I", name: "Attica" },
      { id: "GR-J", name: "Peloponnese" },
      { id: "GR-K", name: "North Aegean" },
      { id: "GR-L", name: "South Aegean" },
      { id: "GR-M", name: "Crete" },
    ],
  },
  {
    id: 13,
    country: "Hungary",
    phoneCode: "+36",
    states: [
      { id: "HU-BA", name: "Baranya" },
      { id: "HU-BK", name: "Bács-Kiskun" },
      { id: "HU-BE", name: "Békés" },
      { id: "HU-BZ", name: "Borsod-Abaúj-Zemplén" },
      { id: "HU-BU", name: "Budapest" },
      { id: "HU-CS", name: "Csongrád-Csanád" },
      { id: "HU-FE", name: "Fejér" },
      { id: "HU-GY", name: "Győr-Moson-Sopron" },
      { id: "HU-HB", name: "Hajdú-Bihar" },
      { id: "HU-HE", name: "Heves" },
      { id: "HU-JN", name: "Jász-Nagykun-Szolnok" },
      { id: "HU-KE", name: "Komárom-Esztergom" },
      { id: "HU-NO", name: "Nógrád" },
      { id: "HU-PE", name: "Pest" },
      { id: "HU-SO", name: "Somogy" },
      { id: "HU-SZ", name: "Szabolcs-Szatmár-Bereg" },
      { id: "HU-TO", name: "Tolna" },
      { id: "HU-VA", name: "Vas" },
      { id: "HU-VE", name: "Veszprém" },
      { id: "HU-ZA", name: "Zala" },
    ],
  },
  {
    id: 14,
    country: "Ireland",
    phoneCode: "+353",
    states: [
      { id: "IE-C", name: "Connacht" },
      { id: "IE-L", name: "Leinster" },
      { id: "IE-M", name: "Munster" },
      { id: "IE-U", name: "Ulster" },
    ],
  },
  {
    id: 15,
    country: "Italy",
    phoneCode: "+39",
    states: [
      { id: "IT-21", name: "Piedmont" },
      { id: "IT-23", name: "Aosta Valley" },
      { id: "IT-25", name: "Lombardy" },
      { id: "IT-27", name: "Trentino-Alto Adige/Südtirol" },
      { id: "IT-28", name: "Veneto" },
      { id: "IT-30", name: "Friuli-Venezia Giulia" },
      { id: "IT-32", name: "Liguria" },
      { id: "IT-33", name: "Emilia-Romagna" },
      { id: "IT-34", name: "Tuscany" },
      { id: "IT-36", name: "Umbria" },
      { id: "IT-37", name: "Marche" },
      { id: "IT-38", name: "Lazio" },
      { id: "IT-40", name: "Abruzzo" },
      { id: "IT-42", name: "Molise" },
      { id: "IT-44", name: "Campania" },
      { id: "IT-45", name: "Apulia" },
      { id: "IT-47", name: "Basilicata" },
      { id: "IT-48", name: "Calabria" },
      { id: "IT-62", name: "Sicily" },
      { id: "IT-65", name: "Sardinia" },
    ],
  },
  {
    id: 16,
    country: "Latvia",
    phoneCode: "+371",
    states: [
      { id: "LV-005", name: "Aizkraukle Municipality" },
      { id: "LV-010", name: "Alūksne Municipality" },
      { id: "LV-013", name: "Balvi Municipality" },
      { id: "LV-015", name: "Bauska Municipality" },
      { id: "LV-021", name: "Cēsis Municipality" },
      { id: "LV-031", name: "Daugavpils" },
      { id: "LV-030", name: "Daugavpils Municipality" },
      { id: "LV-037", name: "Dobele Municipality" },
      { id: "LV-042", name: "Gulbene Municipality" },
      { id: "LV-050", name: "Jelgava" },
      { id: "LV-049", name: "Jelgava Municipality" },
      { id: "LV-056", name: "Jēkabpils Municipality" },
      { id: "LV-062", name: "Kraslava Municipality" },
      { id: "LV-063", name: "Kuldīga Municipality" },
      { id: "LV-067", name: "Liepāja" },
      { id: "LV-069", name: "Limbaži Municipality" },
      { id: "LV-073", name: "Ludza Municipality" },
      { id: "LV-078", name: "Madona Municipality" },
      { id: "LV-080", name: "Ogre Municipality" },
      { id: "LV-083", name: "Preiļi Municipality" },
      { id: "LV-086", name: "Rēzekne" },
      { id: "LV-085", name: "Rēzekne Municipality" },
      { id: "LV-091", name: "Riga" },
      { id: "LV-090", name: "Riga Municipality" },
      { id: "LV-097", name: "Saldus Municipality" },
      { id: "LV-099", name: "Talsi Municipality" },
      { id: "LV-101", name: "Tukums Municipality" },
      { id: "LV-106", name: "Valka Municipality" },
      { id: "LV-105", name: "Valmiera" },
      { id: "LV-109", name: "Ventspils" },
      { id: "LV-108", name: "Ventspils Municipality" },
    ],
  },
  {
    id: 17,
    country: "Lithuania",
    phoneCode: "+370",
    states: [
      { id: "LT-AL", name: "Alytus County" },
      { id: "LT-KU", name: "Kaunas County" },
      { id: "LT-KL", name: "Klaipėda County" },
      { id: "LT-MR", name: "Marijampolė County" },
      { id: "LT-PN", name: "Panevėžys County" },
      { id: "LT-SA", name: "Šiauliai County" },
      { id: "LT-TA", name: "Tauragė County" },
      { id: "LT-TE", name: "Telšiai County" },
      { id: "LT-UT", name: "Utena County" },
      { id: "LT-VL", name: "Vilnius County" },
    ],
  },
  {
    id: 18,
    country: "Luxembourg",
    phoneCode: "+352",
    states: [
      { id: "LU-DI", name: "Diekirch" },
      { id: "LU-GR", name: "Grevenmacher" },
      { id: "LU-LU", name: "Luxembourg" },
    ],
  },
  {
    id: 19,
    country: "Malta",
    states: [
      { id: "MT-49", name: "Ħaż-Żebbuġ" },
      { id: "MT-08", name: "Birkirkara" },
      { id: "MT-64", name: "Ħal Qormi" },
      { id: "MT-40", name: "Marsaskala" },
      { id: "MT-47", name: "Mosta" },
      { id: "MT-57", name: "San Pawl il-Baħar" },
      { id: "MT-60", name: "Sliema" },
      { id: "MT-58", name: "Swieqi" },
      { id: "MT-67", name: "Valletta" },
    ],
  },

  {
    id: 20,
    country: "Netherlands",
    phoneCode: "+31",
    states: [
      { id: "NL-DR", name: "Drenthe" },
      { id: "NL-FL", name: "Flevoland" },
      { id: "NL-FR", name: "Friesland" },
      { id: "NL-GE", name: "Gelderland" },
      { id: "NL-GR", name: "Groningen" },
      { id: "NL-LI", name: "Limburg" },
      { id: "NL-NB", name: "North Brabant" },
      { id: "NL-NH", name: "North Holland" },
      { id: "NL-OV", name: "Overijssel" },
      { id: "NL-UT", name: "Utrecht" },
      { id: "NL-ZE", name: "Zeeland" },
      { id: "NL-ZH", name: "South Holland" },
    ],
  },
  {
    id: 21,
    country: "Poland",
    phoneCode: "+48",
    states: [
      { id: "PL-DS", name: "Lower Silesian Voivodeship" },
      { id: "PL-KP", name: "Kuyavian-Pomeranian Voivodeship" },
      { id: "PL-LB", name: "Lubusz Voivodeship" },
      { id: "PL-LD", name: "Łódź Voivodeship" },
      { id: "PL-LU", name: "Lublin Voivodeship" },
      { id: "PL-MA", name: "Lesser Poland Voivodeship" },
      { id: "PL-MZ", name: "Masovian Voivodeship" },
      { id: "PL-OP", name: "Opole Voivodeship" },
      { id: "PL-PK", name: "Subcarpathian Voivodeship" },
      { id: "PL-PD", name: "Podlaskie Voivodeship" },
      { id: "PL-PM", name: "Pomeranian Voivodeship" },
      { id: "PL-SL", name: "Silesian Voivodeship" },
      { id: "PL-SK", name: "Świętokrzyskie Voivodeship" },
      { id: "PL-WN", name: "Warmian-Masurian Voivodeship" },
      { id: "PL-WP", name: "Greater Poland Voivodeship" },
      { id: "PL-ZP", name: "West Pomeranian Voivodeship" },
    ],
  },
  {
    id: 22,
    country: "Portugal",
    phoneCode: "+351",
    states: [
      { id: "PT-01", name: "Aveiro" },
      { id: "PT-02", name: "Beja" },
      { id: "PT-03", name: "Braga" },
      { id: "PT-04", name: "Bragança" },
      { id: "PT-05", name: "Castelo Branco" },
      { id: "PT-06", name: "Coimbra" },
      { id: "PT-07", name: "Évora" },
      { id: "PT-08", name: "Faro" },
      { id: "PT-09", name: "Guarda" },
      { id: "PT-10", name: "Leiria" },
      { id: "PT-11", name: "Lisbon" },
      { id: "PT-12", name: "Portalegre" },
      { id: "PT-13", name: "Porto" },
      { id: "PT-14", name: "Santarém" },
      { id: "PT-15", name: "Setúbal" },
      { id: "PT-16", name: "Viana do Castelo" },
      { id: "PT-17", name: "Vila Real" },
      { id: "PT-18", name: "Viseu" },
      { id: "PT-20", name: "Azores" },
      { id: "PT-30", name: "Madeira" },
    ],
  },
  {
    id: 23,
    country: "Romania",
    phoneCode: "+40",
    states: [
      { id: "RO-AB", name: "Alba" },
      { id: "RO-AR", name: "Arad" },
      { id: "RO-AG", name: "Argeș" },
      { id: "RO-BC", name: "Bacău" },
      { id: "RO-BH", name: "Bihor" },
      { id: "RO-BN", name: "Bistrița-Năsăud" },
      { id: "RO-BT", name: "Botoșani" },
      { id: "RO-BV", name: "Brașov" },
      { id: "RO-BR", name: "Brăila" },
      { id: "RO-B", name: "Bucharest" },
      { id: "RO-BZ", name: "Buzău" },
      { id: "RO-CL", name: "Călărași" },
      { id: "RO-CS", name: "Caraș-Severin" },
      { id: "RO-CJ", name: "Cluj" },
      { id: "RO-CT", name: "Constanța" },
      { id: "RO-CV", name: "Covasna" },
      { id: "RO-DB", name: "Dâmbovița" },
      { id: "RO-DJ", name: "Dolj" },
      { id: "RO-GL", name: "Galați" },
      { id: "RO-GR", name: "Giurgiu" },
      { id: "RO-GJ", name: "Gorj" },
      { id: "RO-HR", name: "Harghita" },
      { id: "RO-HD", name: "Hunedoara" },
      { id: "RO-IL", name: "Ialomița" },
      { id: "RO-IS", name: "Iași" },
      { id: "RO-IF", name: "Ilfov" },
      { id: "RO-MM", name: "Maramureș" },
      { id: "RO-MH", name: "Mehedinți" },
      { id: "RO-MS", name: "Mureș" },
      { id: "RO-NT", name: "Neamț" },
      { id: "RO-OT", name: "Olt" },
      { id: "RO-PH", name: "Prahova" },
      { id: "RO-SJ", name: "Sălaj" },
      { id: "RO-SM", name: "Satu Mare" },
      { id: "RO-SB", name: "Sibiu" },
      { id: "RO-SV", name: "Suceava" },
      { id: "RO-TR", name: "Teleorman" },
      { id: "RO-TM", name: "Timiș" },
      { id: "RO-TL", name: "Tulcea" },
      { id: "RO-VL", name: "Vâlcea" },
      { id: "RO-VS", name: "Vaslui" },
      { id: "RO-VN", name: "Vrancea" },
    ],
  },
  {
    id: 24,
    country: "Slovakia",
    phoneCode: "+421",
    states: [
      { id: "SK-BC", name: "Banská Bystrica Region" },
      { id: "SK-BL", name: "Bratislava Region" },
      { id: "SK-KI", name: "Košice Region" },
      { id: "SK-NI", name: "Nitra Region" },
      { id: "SK-PV", name: "Prešov Region" },
      { id: "SK-TC", name: "Trenčín Region" },
      { id: "SK-TV", name: "Trnava Region" },
      { id: "SK-ZI", name: "Žilina Region" },
    ],
  },

  {
    id: 25,
    country: "Slovenia",
    phoneCode: "+386",
    states: [
      { id: "SI-084", name: "Luče" },
      { id: "SI-085", name: "Lukovica" },
      { id: "SI-086", name: "Majšperk" },
      { id: "SI-087", name: "Maribor" },
      { id: "SI-088", name: "Markovci" },
      { id: "SI-089", name: "Medvode" },
      { id: "SI-090", name: "Mengeš" },
      { id: "SI-091", name: "Metlika" },
      { id: "SI-092", name: "Mežica" },
      { id: "SI-093", name: "Miren–Kostanjevica" },
      { id: "SI-094", name: "Mirna" },
      { id: "SI-095", name: "Mirna Peč" },
      { id: "SI-096", name: "Mokronog–Trebelno" },
      { id: "SI-097", name: "Murska Sobota" },
      { id: "SI-098", name: "Muta" },
      { id: "SI-099", name: "Naklo" },
      { id: "SI-100", name: "Nazarje" },
      { id: "SI-101", name: "Nova Gorica" },
      { id: "SI-102", name: "Nova vas" },
      { id: "SI-103", name: "Novo mesto" },
      { id: "SI-104", name: "Odranci" },
      { id: "SI-105", name: "Oplotnica" },
      { id: "SI-106", name: "Ormož" },
      { id: "SI-107", name: "Osilnica" },
      { id: "SI-108", name: "Pesnica" },
      { id: "SI-109", name: "Piran/Pirano" },
      { id: "SI-110", name: "Pivka" },
      { id: "SI-111", name: "Podčetrtek" },
      { id: "SI-112", name: "Podlehnik" },
      { id: "SI-113", name: "Podvelka" },
      { id: "SI-114", name: "Poljčane" },
      { id: "SI-115", name: "Polzela" },
      { id: "SI-116", name: "Postojna" },
      { id: "SI-117", name: "Prebold" },
      { id: "SI-118", name: "Preddvor" },
      { id: "SI-119", name: "Prevalje" },
      { id: "SI-120", name: "Ptuj" },
      { id: "SI-121", name: "Puconci" },
      { id: "SI-122", name: "Rače–Fram" },
      { id: "SI-123", name: "Radeče" },
      { id: "SI-124", name: "Radenci" },
      { id: "SI-125", name: "Radlje ob Dravi" },
      { id: "SI-126", name: "Radovljica" },
      { id: "SI-127", name: "Ravne na Koroškem" },
      { id: "SI-128", name: "Razkrižje" },
      { id: "SI-129", name: "Rečica ob Savinji" },
      { id: "SI-130", name: "Renče–Vogrsko" },
      { id: "SI-131", name: "Ribnica" },
      { id: "SI-132", name: "Ribnica na Pohorju" },
      { id: "SI-133", name: "Rogaška Slatina" },
      { id: "SI-134", name: "Rogašovci" },
      { id: "SI-135", name: "Rogatec" },
      { id: "SI-136", name: "Ruše" },
      { id: "SI-137", name: "Šalovci" },
      { id: "SI-138", name: "Šempeter–Vrtojba" },
      { id: "SI-139", name: "Šenčur" },
      { id: "SI-140", name: "Šentilj" },
      { id: "SI-141", name: "Šentjernej" },
      { id: "SI-142", name: "Šentjur" },
      { id: "SI-143", name: "Škocjan" },
      { id: "SI-144", name: "Škofja Loka" },
      { id: "SI-145", name: "Škofljica" },
      { id: "SI-146", name: "Šmarje pri Jelšah" },
      { id: "SI-147", name: "Šmarješke Toplice" },
      { id: "SI-148", name: "Šmartno ob Paki" },
      { id: "SI-149", name: "Šmartno pri Litiji" },
      { id: "SI-150", name: "Sodražica" },
      { id: "SI-151", name: "Solčava" },
      { id: "SI-152", name: "Središče ob Dravi" },
      { id: "SI-153", name: "Starše" },
      { id: "SI-154", name: "Straža" },
      { id: "SI-155", name: "Sveta Ana" },
      { id: "SI-156", name: "Sveta Trojica v Slovenskih goricah" },
      { id: "SI-157", name: "Sveti Andraž v Slovenskih goricah" },
      { id: "SI-158", name: "Sveti Jurij ob Ščavnici" },
      { id: "SI-159", name: "Sveti Jurij v Slovenskih goricah" },
      { id: "SI-160", name: "Tabor" },
      { id: "SI-161", name: "Tišina" },
      { id: "SI-162", name: "Tolmin" },
      { id: "SI-163", name: "Trbovlje" },
      { id: "SI-164", name: "Trebnje" },
      { id: "SI-165", name: "Trzin" },
      { id: "SI-166", name: "Tržič" },
      { id: "SI-167", name: "Turnišče" },
      { id: "SI-168", name: "Velenje" },
      { id: "SI-169", name: "Velika Polana" },
      { id: "SI-170", name: "Velike Lašče" },
      { id: "SI-171", name: "Veržej" },
      { id: "SI-172", name: "Videm" },
      { id: "SI-173", name: "Videm Dobrepolje" },
      { id: "SI-174", name: "Vipava" },
      { id: "SI-175", name: "Vitanje" },
      { id: "SI-176", name: "Vodice" },
      { id: "SI-177", name: "Vojnik" },
      { id: "SI-178", name: "Vransko" },
      { id: "SI-179", name: "Vrhnika" },
      { id: "SI-180", name: "Vuzenica" },
      { id: "SI-181", name: "Zagorje ob Savi" },
      { id: "SI-182", name: "Žalec" },
      { id: "SI-183", name: "Železniki" },
      { id: "SI-184", name: "Žetale" },
      { id: "SI-185", name: "Žiri" },
      { id: "SI-186", name: "Žirovnica" },
      { id: "SI-187", name: "Žužemberk" },
    ],
  },
  {
    id: 26,
    country: "Spain",
    phoneCode: "+34",
    states: [
      { id: "ES-AN", name: "Andalusia" },
      { id: "ES-AR", name: "Aragon" },
      { id: "ES-AS", name: "Asturias, Principality of" },
      { id: "ES-IB", name: "Balearic Islands" },
      { id: "ES-PV", name: "Basque Country" },
      { id: "ES-CN", name: "Canary Islands" },
      { id: "ES-CB", name: "Cantabria" },
      { id: "ES-CL", name: "Castile and León" },
      { id: "ES-CM", name: "Castile-La Mancha" },
      { id: "ES-CT", name: "Catalonia" },
      { id: "ES-EX", name: "Extremadura" },
      { id: "ES-GA", name: "Galicia" },
      { id: "ES-RI", name: "La Rioja" },
      { id: "ES-MD", name: "Madrid, Community of" },
      { id: "ES-MC", name: "Murcia, Region of" },
      { id: "ES-NC", name: "Navarre, Chartered Community of" },
      { id: "ES-VC", name: "Valencian Community" },
    ],
  },
  {
    id: 27,
    country: "Sweden",
    phoneCode: "+46",
    states: [
      { id: "SE-K", name: "Blekinge County" },
      { id: "SE-W", name: "Dalarna County" },
      { id: "SE-I", name: "Gotland County" },
      { id: "SE-X", name: "Gävleborg County" },
      { id: "SE-N", name: "Halland County" },
      { id: "SE-Z", name: "Jämtland County" },
      { id: "SE-F", name: "Jönköping County" },
      { id: "SE-H", name: "Kalmar County" },
      { id: "SE-G", name: "Kronoberg County" },
      { id: "SE-BD", name: "Norrbotten County" },
      { id: "SE-M", name: "Skåne County" },
      { id: "SE-AB", name: "Stockholm County" },
      { id: "SE-D", name: "Södermanland County" },
      { id: "SE-S", name: "Uppsala County" },
      { id: "SE-Y", name: "Västernorrland County" },
      { id: "SE-U", name: "Västmanland County" },
      { id: "SE-O", name: "Västra Götaland County" },
      { id: "SE-T", name: "Örebro County" },
      { id: "SE-E", name: "Östergötland County" },
    ],
  },
];
